### ISSUE TITLE
Don't use latest tag in container registry

### ISSUE THREAD

**Issue by mecampbellsoup** [crazy-max/docker-7zip#19]
Hello sir.

I want to use your image since it's more or less done already, but there is one issue I would like to point out.

Please do not use `latest` as a tag: https://vsupalov.com/docker-latest-tag/#:~:text=The%20Kubernetes%20docs%20are%20pretty,and%20hard%20to%20roll%20back

If we depend on this image and you change the version that is referenced by the `latest` tag (and it in turn breaks our code) we have no way of preventing that.

Please amend your CI flow to at least build and register images w/ fixed versions that we can rely on to be immutable. Thanks!

**Comment by crazy-max** [comment]
@mecampbellsoup Sure we can do that.

**Comment by mecampbellsoup** [comment]
@crazy-max where is the CI configuration?

Is it [this](https://github.com/crazy-max/docker-7zip/blob/b24ddab5d878d6ace20ea63712837deb49b437c9/.github/workflows/build.yml#L36)?

**Comment by crazy-max** [comment]
Done: https://hub.docker.com/r/crazymax/7zip/tags?page=1&ordering=last_updated
