### ISSUE TITLE
Can't load './7z.dll' (Dynamic loading not supported)

### ISSUE THREAD

**Issue by eleaner** [crazy-max/docker-7zip#34]
I am trying to run this container to encrypt a file and I am getting this error
```
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Can't load './7z.dll' (Dynamic loading not supported)


ERROR:
7-Zip cannot find the code that works with archives.
```

**Comment by eleaner** [comment]
image tag 16:02 seem to be working just fine

**Comment by crazy-max** [comment]
What command?

**Comment by eleaner** [comment]
docker run --rm --workdir /data -it -v $BACKUP_DIR:/data crazymax/7zip:16.02 7z a $archive $file

16.02 works
latest etc give error

**Comment by crazy-max** [comment]
Oh I see you're using the `7z` command. Can you try with `7za` instead? I think I should just symlink to `7za` instead of moving `7z_`: https://github.com/crazy-max/docker-7zip/blob/8ce02ac39f2625c460a0d0ef1f37fdf1ac001260/Dockerfile#L29

**Comment by crazy-max** [comment]
I will also look at switching to https://7-zip.org/ releases instead of p7zip.
